import { Geist, DM_Sans } from 'next/font/google';
import './globals.css';
import { Suspense } from 'react';
import CircularLoading from './components/common/loader/Loader';
import { Toaster } from 'react-hot-toast';

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist',
  display: 'swap',
});

const dmSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dm-sans',
  display: 'swap',
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// export const metadata= {
//   title: "MapleRecord",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geist.variable} ${dmSans.variable} antialiased`}>
        <Toaster position="top-center" />
        <Suspense fallback={<CircularLoading />}>
          {/* <div className=" p-[0_12px_12px] bg-white"> */}
          {children}
          {/* </div> */}
        </Suspense>
      </body>
    </html>
  );
}
